<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-LX-JXGM2X2" ignored="0" name="Test" tests="6" failures="1" timestamp="15 Nov 2020 06:04:14 GMT" time="0.066" errors="0">
  <testcase name="Test1" time="0.018" classname="rough.testRetry"/>
  <testcase name="Test2" time="0.003" classname="rough.testRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="rough.testRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="rough.testRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="rough.testRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="rough.testRetry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rough.testRetry.Test2(testRetry.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test -->
